### ISSUE TITLE
Hawthorn GeneratedCertificate Mock is wrong

### ISSUE THREAD

**Issue by johnbaldwin** [appsembler/figures#332]
As you discovered, @estherjsuh , the `GeneratedCertificate` mock is wrong, missing the `
In Hawthorn, the `on_delete=models.CASCADE` in the mock code:

This is the production model:

https://github.com/appsembler/edx-platform/blob/appsembler/tahoe/master/lms/djangoapps/certificates/models.py#L233

So we need to fix this for the Hawthorn mock
- https://github.com/appsembler/figures/blob/master/mocks/hawthorn/lms/djangoapps/certificates/models.py#L9

The Juniper mock looks correct: https://github.com/appsembler/figures/blob/master/mocks/juniper/lms/djangoapps/certificates/models.py#L11

**Comment by estherjsuh** [comment]
Hi @johnbaldwin, I linked a PR for this issue.
Please review. Thanks!
