### ISSUE TITLE
Make the integration with Open edX more seamless

### ISSUE THREAD

**Issue by OmarIthawi** [appsembler/figures#40]
Going through the README I see several requests to edit the settings. I'd like to suggest better alternatives:

``pip install figures``
That's great! It's much faster than git!

---

```
	"ADDL_INSTALLED_APPS": [
		"figures"
	]
```
This is acceptable practice, especially if there's migrations (such as in this case).

----

```
	"FEATURES": {
		... 
		"ENABLE_FIGURES": true,
		...
	}
```
In my opinion this is redundant, since we're adding the app to `ADDL_INSTALLED_APPS`, there's no need to have a feature, it's not like being a feature inside the edX platform.

----

```
from figures.settings import FIGURES
```

Please avoid this pattern, there's about 200 dependencies/apps in the edX Platform almost none of them uses this pattern. This pattern is problematic since Figures depends on the settings and I don't see any need why settings would depend on Figures.

----

```
	if FEATURES.get('ENABLE_FIGURES'):
		from figures.settings import FIGURES
```
Sames goes here.

```
if settings.FEATURES.get('ENABLE_FIGURES'):
    	urlpatterns += (
    		url(r'^figures/',
    		    include('figures.urls', namespace='figures')),
    	)
```

`if settings.FEATURES.get('ENABLE_FIGURES'):` -> `'figures' in if settings.INSTALLED_APPS'):`

----

The way static files is integrated should be completely decoupled from the edX Platform such as:

 1. The platform should know nothing about how the static files are manages.
 2. Figures should know nothing about how the platform manages its static files.
 3. Static assets such as compiled `js` and `css` files should be committed to the git repo.
 4. Figures views should call those files, the [XBlock `ResourceLoader`](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/master/drag_and_drop_v2/drag_and_drop_v2.py#L27) is a good [example of such pattern](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/master/drag_and_drop_v2/drag_and_drop_v2.py#L272-L275).

**Comment by OmarIthawi** [comment]
cc: @johnbaldwin

**Comment by johnbaldwin** [comment]
@OmarIthawi Can you suggest a replacement for the code in Figures settings that will do the following without modifying edx-platform or having Figures inject entries into the settings?

A) add figures to edx-platform's `WEBPACK_LOADER`

B) Add Figures to edx-platform's `CELERYBEAT_SCHEDULE`. Since Ficus and Ginkgo don't seem to have database based Celery scheduling, we need to add to the `CELERYBEAT_SCHEDULE` in the LMS envs.

**Comment by johnbaldwin** [comment]
@OmarIthawi I created a new issues to address your specific comment on `ENABLE_FIGURES` in the `FEATURES` section of the server vars.

This makes sense and I can check if Figures is in the `INSTALLED_APPS` to see if we're going to load Figures settings in order to add entries to `WEBPACK_LOADER` and `CELERYBEAT_SCHEDULE`

I'll update the Ginkgo and Ficus Appsembler feature branches and the README to reflect this

**Comment by l1ph0x** [comment]
Apologies in advance, if my comment below does not belong here, and if it is an unrelated issue.
I am running a native install of open-release/ginkgo.master. I have installed Appsembler's Figures following the how to for production env found [here](https://github.com/appsembler/figures/blob/develop/docs/source/install.rst). After successfully migrating and restarting the services figures tab does not show under user's (staff) tab. I compiled (java script) assets, too. Still no effect. I think WebPack somehow does not load it but I do not know how to debug it.

**Comment by OmarIthawi** [comment]
@l1ph0x there's no tab yet. Perhaps you'd like to create a new issue for it.

**Comment by l1ph0x** [comment]
@OmarIthawi Thanks a lot for your reply. I saw a [demo](https://www.appsembler.com/blog/an-inside-look-at-figures-a-better-way-to-measure-course-performance-in-open-edx/) on Appsember's website. And that is where my assumption came from. So far everything works very well on my intall of Apsembler's Figures. So, I had better wait for Devs to decide whether there is going a tab or not, and if yes, where it would go.

**Comment by OmarIthawi** [comment]
This has been resolved. Closing.
