### ISSUE TITLE
Release a non-dev 0.4.x release

### ISSUE THREAD

**Issue by OmarIthawi** [appsembler/figures#411]
We've been releasing `v0.4.dev` releases for over a year, I think it's now time to release a non-dev release.

 - See: Release history on PyPI: https://pypi.org/project/Figures/#history

**Comment by johnbaldwin** [comment]
@OmarIthawi Works for me. Also, I'm updating Figures release management docs in Confluence, and will then update the repo docs here for the community once we've agreed

**Comment by OmarIthawi** [comment]
Fixed by #415
