### ISSUE TITLE
Document Figures and Open edX versions compatibility table

### ISSUE THREAD

**Issue by OmarIthawi** [appsembler/figures#436]
I'd like to make an up to date version compatibility table. The table can be inferred from the change log but it's good to have it summarized somewhere else.

### Figures released versions
Here's the table I'm starting with:

| Figures version  | Open edX release(s) | Support status | Note |
| --- | --- | --- | --- |
| `v0.4.x` | Ginkgo, Hawthorn and Juniper  | Supported | Juniper support added  |
| `v0.3.x` | Ginkgo, Hawthorn  | Support ended | Hawthorn support added  |
| `v0.2.x` | Ficus, Ginkgo | Support ended | First Tahoe compatible release with multi-site support  |
| `v0.1.x` | Ficus, Ginkgo | Support ended | First release of Figures with single site support |

### Tentative versions
Once we decide on the plan for Maple and Koa, probably we'll need to add the following rows:

| Figures version  | Open edX release(s) | Support status | Note |
| --- | --- | --- | --- |
| `v0.10.x` | Maple  | Not ready, in development | Maple support being added  |
| `v0.5.x` | Juniper, Koa  | Undecided yet | Add Koa support, drop Ginkgo and Hawthorn. Use upstream `edx-organizations` instead of Tahoe fork. |

### Questions

 - Apart from the tentative items, is the table accurate?
 - Where can I publish this table?

   * Option 1: REDME.md
   * Option 2: VERSIONS.md
   * Option 3: GitHub wiki page: https://github.com/appsembler/figures/wiki

[Omar] I prefer README.md but other options are also good.

**Comment by johnbaldwin** [comment]
I've started to overhaul the main README, which is now mostly filled with changelog info. I'll add this to the new format README
